/*
 * PagarmeCoreApi.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using PagarmeCoreApi.PCL;
using PagarmeCoreApi.PCL.Utilities;
using PagarmeCoreApi.PCL.Http.Request;
using PagarmeCoreApi.PCL.Http.Response;
using PagarmeCoreApi.PCL.Http.Client;

namespace PagarmeCoreApi.PCL.Controllers
{
    public partial interface ITransfersController
    {
        /// <summary>
        /// Gets all transfers
        /// </summary>
        /// <return>Returns the Models.ListTransfers response from the API call</return>
        Models.ListTransfers GetTransfers1();

        /// <summary>
        /// Gets all transfers
        /// </summary>
        /// <return>Returns the Models.ListTransfers response from the API call</return>
        Task<Models.ListTransfers> GetTransfers1Async();

        /// <summary>
        /// GetTransferById
        /// </summary>
        /// <param name="transferId">Required parameter: Example: </param>
        /// <return>Returns the Models.GetTransfer response from the API call</return>
        Models.GetTransfer GetTransferById(string transferId);

        /// <summary>
        /// GetTransferById
        /// </summary>
        /// <param name="transferId">Required parameter: Example: </param>
        /// <return>Returns the Models.GetTransfer response from the API call</return>
        Task<Models.GetTransfer> GetTransferByIdAsync(string transferId);

        /// <summary>
        /// CreateTransfer
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.GetTransfer response from the API call</return>
        Models.GetTransfer PostCreateTransfer(Models.CreateTransfer body);

        /// <summary>
        /// CreateTransfer
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.GetTransfer response from the API call</return>
        Task<Models.GetTransfer> PostCreateTransferAsync(Models.CreateTransfer body);

    }
} 