/*
 * PagarmeCoreApi.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using PagarmeCoreApi.PCL;
using PagarmeCoreApi.PCL.Utilities; 
using PagarmeCoreApi.PCL.Http.Client;
using PagarmeCoreApi.PCL.Http.Response;
using PagarmeCoreApi.Tests.Helpers;
using NUnit.Framework;
using PagarmeCoreApi.PCL;
using PagarmeCoreApi.PCL.Controllers;
using PagarmeCoreApi.PCL.Exceptions;

namespace PagarmeCoreApi.Tests
{
    [TestFixture]
    public class CustomersControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static ICustomersController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().Customers;
        }

        /// <summary>
        /// Get all Customers 
        /// </summary>
        [Test]
        public async Task TestTestGetCustomers() 
        {
            // Parameters for the API call
            string name = null;
            string document = null;
            int? page = 1;
            int? size = 10;
            string email = null;
            string code = null;

            // Perform API call
            PCL.Models.ListCustomersResponse result = null;

            try
            {
                result = await controller.GetCustomersAsync(name, document, page, size, email, code);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

        }

    }
}